### ISSUE TITLE
Add Docker support: Tracking docker issues here

### ISSUE THREAD

**Issue by JackDallas** [JackDallas/Premiumizearr#16]
[Wanted here](https://github.com/JackDallas/Premiumizearr/issues/15)

- [x] Add Dockerfile for amd64
- [x] Auto publish releases to github
- [ ] (maybe) Publish releases to docker hub

**Comment by JackDallas** [comment]
https://github.com/JackDallas/Premiumizearr/issues/15

**Comment by JackDallas** [comment]
Please leave any issues with the initial docker release here

**Comment by JRDevo** [comment]
I seem to be getting auth & 404 issues:

The URL under the Docker instructions returns a 404
https://github.com/jackdallas/Premiumizearr/pkgs/container/premiumizearr

Running the docker command returns "unauthorized".

sudo docker run ghcr.io/jackdallas/premiumizearr:latest /volumeUSB2/usbshare/config/premiumizearr/config.yaml:/opt/app/config.yaml -v /volume1/Downloads:/downloads -v /volumeUSB2/usbshare/downloads/blackhole:/blackhole

Unable to find image 'ghcr.io/jackdallas/premiumizearr:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/jackdallas/premiumizearr/manifests/latest": **unauthorized.**
See 'docker run --help'.

**Comment by phildapunk** [comment]
Similar to JRDevo, but I have also logged in to ghcr in the terminal session , but receive a Denied response when trying to pull the image

**Comment by JackDallas** [comment]
Hi there, yeah it seems there's been an error somewhere in the upload process for docker, my bad I should have checked on it, I'll endeavour to get this resolved on the weekend, been a bit swamped this week I'm afraid, I'll pot back here when it's looking like it's working :+1:

**Comment by JackDallas** [comment]
@JRDevo @phildapunk Issue with the docker access should be fixed now, And I'm working on an update with a fixes, sorry for the delay I managed to get COVID and only just got round to updating my github projects

**Comment by JRDevo** [comment]
Hi Jack,

I had some success with the following:

sudo docker run -d \
  --name=premiumizearr2 \
  -v /volumeUSB2/usbshare/config/premiumizearr/config.yaml:/opt/app/config.yaml \
  -e PUID=1033 \
  -e PGID=100 \
  -e TZ=Europe/Amsterdam \
  -p 8182:8182 \
  -v /volume1/Downloads:/downloads \
  -v /volumeUSB2/usbshare/downloads/blackhole:/blackhole \
  --restart unless-stopped \
  ghcr.io/jackdallas/premiumizearr:latest

Created the container successfully

Container logs:

time="2022-05-14T20:08:37Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-14T20:08:37Z" level=info
time="2022-05-14T20:08:37Z" level=info msg="Starting directory watcher..."
time="2022-05-14T20:08:37Z" level=error msg="Error getting folders: Get \"https://www.premiumize.me/api/folder/list?apikey=APIKEY\": x509: certificate signed by unknown authority"
time="2022-05-14T20:08:37Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"

**Comment by JRDevo** [comment]
Hi Jack,

I built and image using the dockerfile:

```
FROM ubuntu:latest

RUN apt update && \
    apt install openssl -y && \
    apt install ca-certificates

WORKDIR /opt/app/

COPY premiumizearrd /opt/app/
COPY static /opt/app/static/
EXPOSE 8182

ENTRYPOINT [ "/opt/app/premiumizearrd" ]
```

and seems to have worked using my container script above :)

**Comment by JRDevo** [comment]
Tested with the latest docker file:

time="2022-05-15T18:24:06Z" level=info msg="Starting directory watcher..."
time="2022-05-15T18:24:06Z" level=error msg="Error getting folders: Get \"https://www.premiumize.me/api/folder/list?apikey=APIKEY\": x509: certificate signed by unknown authority"
time="2022-05-15T18:24:06Z" level=fatal msg="Cannot read folders from premiumize.me, exiting!"

Think it has to do with Ubuntu 18?

**Comment by JRDevo** [comment]
Also think we need:

EXPOSE 8182

**Comment by JackDallas** [comment]
No it's my fault I think, I screwed up the tag I think, I'll change to latest and add the expose then re-tag it :+1:

**Comment by JRDevo** [comment]
Try this? Not sure if RM is included with Ubuntu, prob is :)

```
RUN apt update && \
    apt install openssl -y && \
    apt install ca-certificates  && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by JRDevo** [comment]
Hmmm.. I'm not sure if that's the issue, will try again

**Comment by JackDallas** [comment]
Looks fixed to me now as of v1.1.3 don't forget to `docker pull ghcr.io/jackdallas/premiumizearr:latest` if you're using the latest tag, let me know if there's any more issues 👍

**Comment by JRDevo** [comment]
Yup!

Working like a charm :) 
     
time="2022-05-15T19:00:05Z" level=info msg="---------- Starting premiumizearr daemon ----------"
time="2022-05-15T19:00:05Z" level=info
time="2022-05-15T19:00:05Z" level=info msg="Starting directory watcher..."
time="2022-05-15T19:00:05Z" level=info msg="Clearing tmp directory..."
time="2022-05-15T19:00:05Z" level=info msg="Creating Queue..."
time="2022-05-15T19:00:05Z" level=info msg="Starting uploads processor..."
time="2022-05-15T19:00:05Z" level=info msg="Starting initial directory scans..."
time="2022-05-15T19:00:05Z" level=error msg="Directory created in blackhole /blackhole/tv ignoring (Warning premiumizearrzed does not look in subfolders!)"
time="2022-05-15T19:00:05Z" level=error msg="Directory created in blackhole /blackhole/music ignoring (Warning premiumizearrzed does not look in subfolders!)"
time="2022-05-15T19:00:05Z" level=error msg="Directory created in blackhole /blackhole/default ignoring (Warning premiumizearrzed does not look in subfolders!)"
time="2022-05-15T19:00:05Z" level=error msg="Directory created in blackhole /blackhole/movie ignoring (Warning premiumizearrzed does not look in subfolders!)"
time="2022-05-15T19:00:05Z" level=error msg="Directory created in blackhole /blackhole/books ignoring (Warning premiumizearrzed does not look in subfolders!)"

**Comment by JackDallas** [comment]
Okay seems docker is now all good, I'm going to close this and if anyone has any more docker issues feel free to open a new issue
